# Generated by Django 6.0.4 on 2026-04-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to='backend.vendedor')),
                ('razao_social', models.CharField(blank=True, max_length=150)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='backend.vendedor'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='backend.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='backend.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='backend.pedido')),
            ],
        ),
    ]
