# Generated by Django 6.0.4 on 2026-05-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_guerra', models.CharField(max_length=100)),
                ('posicao', models.CharField(choices=[('GOLEIRO', 'Goleiro'), ('ZAGUEIRO', 'Zagueiro'), ('LATERAL', 'Lateral'), ('VOLANTE', 'Volante'), ('MEIO-CAMPISTA', 'Meio-campista'), ('ATACANTE', 'Atacante')], max_length=20)),
                ('nascimento', models.DateField()),
                ('numero_camisa', models.PositiveSmallIntegerField()),
                ('suspenso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('fase de grupos', 'Fase de Grupos'), ('fase de 32', 'Fase de 32'), ('oitavas de final', 'Oitavas de Final'), ('quartas de final', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('disputa de terceiro lugar', 'Disputa de Terceiro Lugar'), ('final', 'Final')], max_length=30)),
                ('data_hora', models.DateTimeField()),
                ('estadio', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('gols_mandante', models.PositiveSmallIntegerField(default=0)),
                ('gols_visitante', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='torneio.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOL', 'Gol'), ('GOL_CONTRA', 'Gol Contra'), ('CARTAO_AMARELO', 'Cartão Amarelo'), ('CARTAO_VERMELHO', 'Cartão Vermelho'), ('SUBSTITUICAO', 'Substituição')], max_length=20)),
                ('minuto', models.PositiveSmallIntegerField()),
                ('acrescimo', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='torneio.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='torneio.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('confedracao', models.CharField(choices=[('CONMEBOL', 'CONMEBOL'), ('UEFA', 'UEFA'), ('CONCACAF', 'CONCACAF'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC')], max_length=10)),
                ('escudo_url', models.URLField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes', to='torneio.grupo')),
                ('tecnico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecao', to='torneio.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='torneio.selecao'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='torneio.selecao'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='selecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='torneio.selecao'),
        ),
    ]
