# Generated by Django 6.0.4 on 2026-05-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecao',
            old_name='confedracao',
            new_name='confederacao',
        ),
    ]
